import Link from 'next/link';
import {
  Zap,
  BotMessageSquare,
  FlaskConical,
  Calculator,
  Users,
  ShieldAlert,
  ArrowRight,
} from 'lucide-react';

export const metadata = {
  title: 'Features — Trading Hub Docs',
};

const FEATURES = [
  {
    icon: Zap,
    title: 'Trading Signals',
    href: '/signals',
    desc: 'Signals are generated by the AI agent after running its 9-step analysis pipeline, or ingested directly from TradingView webhooks. Each signal includes the direction (LONG / SHORT), entry price, stop-loss, take-profit, and a full reasoning breakdown citing every tool that contributed.',
    tag: 'Core',
  },
  {
    icon: BotMessageSquare,
    title: 'AI Chat',
    href: '/chat',
    desc: 'Ask the trading agent anything in plain English. "Analyse SOLUSDT on 1H", "What is the current funding rate on BTC?", "Give me a risk-adjusted position size for a 2% stop." The agent has access to all the same tools as the automated pipeline.',
    tag: 'Core',
  },
  {
    icon: FlaskConical,
    title: 'Backtesting',
    href: '/backtest',
    desc: 'Run historical simulations on any supported pair using the same signal logic as the live agent. Backtests produce an equity curve, per-trade log, win rate, Sharpe ratio, and max drawdown — so you can validate a strategy before committing capital.',
    tag: 'Analysis',
  },
  {
    icon: Calculator,
    title: 'Risk Calculator',
    href: '/risk-calculator',
    desc: 'A standalone tool for manually computing position sizes. Input your account balance, risk percentage, entry price, and stop-loss — it returns position size, potential loss in dollars, and a fee + slippage-adjusted break-even.',
    tag: 'Analysis',
  },
  {
    icon: Users,
    title: 'Copy Trading',
    href: '/copy',
    desc: 'Browse top-performing signal publishers and mirror their trades automatically. Publishers earn a performance fee; subscribers get real-time mirroring with the same risk controls (position limits, kill switch) applied to their account.',
    tag: 'Social',
  },
  {
    icon: ShieldAlert,
    title: 'Paper Mode & Kill Switch',
    href: '/profile/risk',
    desc: 'Paper Trading Mode runs the full pipeline on live data without executing real orders — ideal for validating performance before going live. The Kill Switch halts all new signal execution instantly and can be triggered manually or by hitting your daily loss limit or max drawdown threshold.',
    tag: 'Safety',
  },
];

const TAG_COLORS: Record<string, string> = {
  Core: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/20',
  Analysis: 'text-blue-400 bg-blue-500/10 border-blue-500/20',
  Social: 'text-violet-400 bg-violet-500/10 border-violet-500/20',
  Safety: 'text-amber-400 bg-amber-500/10 border-amber-500/20',
};

export default function FeaturesPage() {
  return (
    <article>
      <p className="text-xs font-semibold uppercase tracking-widest text-emerald-500 mb-2">Features</p>
      <h1 className="text-3xl font-bold text-white mb-3">Everything in one place</h1>
      <p className="text-zinc-400 text-lg mb-12">
        Trading Hub combines AI-generated signals, manual analysis tools, social copy trading, and airtight risk controls — all in a single platform.
      </p>

      <div className="space-y-6">
        {FEATURES.map(({ icon: Icon, title, href, desc, tag }) => (
          <div key={title} className="rounded-xl border border-zinc-800 bg-zinc-900/40 p-6 hover:border-zinc-700 transition-colors">
            <div className="flex items-start justify-between mb-3">
              <div className="flex items-center gap-3">
                <div className="w-9 h-9 rounded-lg bg-zinc-800 flex items-center justify-center shrink-0">
                  <Icon className="h-4.5 w-4.5 text-zinc-300" />
                </div>
                <h2 className="text-base font-semibold text-white">{title}</h2>
              </div>
              <span className={`text-xs font-medium px-2 py-0.5 rounded border ${TAG_COLORS[tag]}`}>
                {tag}
              </span>
            </div>
            <p className="text-zinc-400 text-sm leading-relaxed mb-3">{desc}</p>
            <Link href={href} className="text-xs text-emerald-400 hover:text-emerald-300 transition-colors">
              Open in app →
            </Link>
          </div>
        ))}
      </div>

      <div className="mt-16 rounded-2xl bg-zinc-900/60 border border-zinc-800 p-8 text-center">
        <p className="text-2xl font-bold text-white mb-2">Explore it yourself</p>
        <p className="text-zinc-400 mb-6">Paper trading unlocks every feature — no credit card required.</p>
        <Link
          href="/sign-up"
          className="inline-flex items-center gap-2 rounded-full bg-emerald-500 hover:bg-emerald-400 text-black font-semibold px-8 py-3 transition-colors"
        >
          Get started free <ArrowRight className="h-4 w-4" />
        </Link>
      </div>
    </article>
  );
}
